language: julia

os:
  - linux
#  - osx

branches:
  only:
    - master
    - julia-1.0
  
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: 1.0
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Coverage");'
  - julia -e 'import Plasm; cd(dirname(dirname(pathof(Plasm)))); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Coverage; import Plasm; cd(dirname(dirname(pathof(Plasm)))); Codecov.submit(process_folder())'

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github-token: $GITHUB_TOKEN
#  keep-history: true
#  local-dir: docs/build
#  on:
#    branch: master
